### ISSUE TITLE
Missing Committee Memberships

### ISSUE THREAD

**Issue by pqnelson** [propublica/congress#505]
Hello,

I tried scraping the committees for memberships, but it appears 35 of them are missing members (they have empty arrays).

The problematic committees are:
- the Efficiency and Effectiveness of Federal Programs and the Federal Workforce (SSGA16)
- Financial and Contracting Oversight (SSGA15)
- Emergency Management, Intergovernmental Relations, and the District of Columbia (SSGA17)
- International Operations and Organizations, Human Rights, Democracy, and Global Women's Issues (SSFR13)
- International Development and Foreign Assistance, Economic Affairs, International Environmental Protection, and Peace Corps (SSFR12)
- Oversight (SSEV18)
- Green Jobs and the New Economy (SSEV16)
- Tourism, Competitiveness, and Innovation (SSCM27)
- Economic Growth, Tax and Capital Access (HSSM27)
- Health and Technology (HSSM26)
- Agriculture, Energy and Trade (HSSM25)
- Terrorism, Human Intelligence, Analysis, and Counterintelligence (HLIG08)
- Technical and Tactical Intelligence (HLIG05)
- Oversight and Investigations (HLIG09)
- Transportation, and Housing and Urban Development, and Related Agencies (HSAP20)
- Military Construction, Veterans Affairs, and Related Agencies (HSAP18)
- Legislative Branch (HSAP24)
- Homeland Security (HSAP15)
- Financial Services and General Government (HSAP23)
- Commerce, Justice, Science, and Related Agencies (HSAP19)
- Investigations, Oversight and Regulations (HSSM24)
- Contracting and Workforce (HSSM23)
- Bankruptcy and the Courts (SSJU24)
- Rules and Organization of the House (HSRU04)
- Legislative and Budget Process (HSRU02)
- Economic Growth, Job Creation and Regulatory Affairs (HSGO28)
- Health Care, Benefits and Administrative Rules (HSGO27)
- Federal Workforce, U.S. Postal Service and the Census (HSGO25)
- National Security (HSGO06)
- Labor, Health and Human Services, Education, and Related Agencies (HSAP07)
- Interior, Environment, and Related Agencies (HSAP06)
- State, Foreign Operations, and Related Programs (HSAP04)
- Energy and Water Development, and Related Agencies (HSAP10)
- Defense (HSAP02)
- Agriculture, Rural Development, Food and Drug Administration, and Related Agencies (HSAP01)

**Comment by crdunwel** [comment]
See https://github.com/unitedstates/congress-legislators/issues/252 . The source data needs to be updated here https://github.com/unitedstates/congress-legislators/blob/master/committee-membership-current.yaml .
