### ISSUE TITLE
Many zip codes returning no congressional districts for districts/locate endpoint

### ISSUE THREAD

**Issue by blocher** [propublica/congress#519]
https://congress.api.sunlightfoundation.com/districts/locate?apikey=[REDACTED]&zip=22304

Returns no results, when answer should be VA-08

https://congress.api.sunlightfoundation.com/districts/locate?apikey=[REDACTED]&zip=15317

Correctly returns PA-18

**Comment by crdunwel** [comment]
I've been updated some shape files for districts. Can you check again? Let me know all the specific zips that you've having issues with and I can investigate.

**Comment by ChrisAntaki** [comment]
Seems to be fixed
