### ISSUE TITLE
Minnesota senators have `null` twitter_id's (legislators/locate)

### ISSUE THREAD

**Issue by ChrisAntaki** [propublica/congress#520]
It appears Minnesota's senators don't have their Twitter handles set in your database. Any chance you could add them?

Franken => `alfranken`
Klobuchar => `amyklobuchar`

Thanks!

**Comment by ChrisAntaki** [comment]
I found three more. :wink: 
Cassidy => `BillCassidy`
Paul => `randpaul`
Vitter => `DavidVitter`

**Comment by dwillis** [comment]
We include official Twitter accounts, not personal or campaign ones, which is why the ones you name aren't included.

**Comment by ChrisAntaki** [comment]
Thanks for the update!
