### ISSUE TITLE
Missing bills introduced after July 18th, 2016

### ISSUE THREAD

**Issue by pqnelson** [propublica/congress#524]
It appears HR bills introduced on or after July 18th, 2016 are missing.

The GPO doesn't have a [status](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/hr) for [HR5913-114](https://www.congress.gov/bill/114th-congress/house-bill/5913?resultIndex=14) (or any other such bill introduced after the 18th).

**Comment by dwillis** [comment]
This has been fixed for bills through last week.
