### ISSUE TITLE
Virginia redistricting

### ISSUE THREAD

**Issue by jrmumby** [propublica/congress#526]
/districts/locate is running into trouble in Virginia -- their redistricting plan was overturned and replaced, but the API is still returning the old districts. 

http://www.rollcall.com/news/politics/judges-select-new-virginia-congressional-map

We're using the API to help folks locate their members of Congress and are getting complaints.

Thanks so much for maintaining this resource

**Comment by dwillis** [comment]
The old districts still exist until the end of the year.
