### ISSUE TITLE
Congress Bills API Per_page = all

### ISSUE THREAD

**Issue by veeravn** [propublica/congress#530]
I am using the congress API and need to get 50 active and 50 inactive bills, I am doing this by making an API call with the parameter: per_page=all, but this only gets me 20 results.  Is there a way I can get the 50 active and inactive bills

Thank You.

**Comment by konklone** [comment]
`per_page=all` only works for `/legislators`. You can use 50 results by using `per_page=50`, and making a request for each category of bill you're looking for.
