### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by lhorie** [propublica/congress#532]
e.g. `https://congress.api.sunlightfoundation.com/districts/locate?zip=98119&apikey=[KEY]` returns `502 - Bad Gateway` errors and sometimes `504 - Gateway timeout` errors

**Comment by dwillis** [comment]
Hi @lhorie: we're in the process of transitioning the API to ProPublica's control, and we expect it will be fully up and running in a few days. Parts of it already should be working.

**Comment by timsvoice** [comment]
+1. Is there any way to access the API sooner? NodeKnockout is happening this weekend and would be great to access.

Thanks!

**Comment by dwillis** [comment]
@timsvoice: Most, but not all, of the API is up and running. Same url, but no credentials needed. We're working to get some of the bills responses and a few other pieces running asap.

**Comment by timsvoice** [comment]
@dwillis great. thanks for the quick response!

**Comment by yocheved** [comment]
@dwillis: I have been having the same issues - 502 and 504 responses. When I make the request without any query parameters, then it works - but then I cant set the paging and only receive the first 20 results.
How can I get the apis to work (legislator specifically)? Thank You

**Comment by dwillis** [comment]
@yocheved: can you post some urls that aren't working for you?

**Comment by dwillis** [comment]
To all who commented, please give the endpoints that have been causing problems another try. I think the 502/504 errors should be resolved. If not, please let us know.

**Comment by timsvoice** [comment]
@dwillis all endpoints I'm trying are working great. Thanks!

**Comment by yocheved** [comment]
@dwillis: I checked now and all endpoint seem to be working. Thank you very much!

**Comment by yocheved** [comment]
@dwillis I checked again now and all endpoints seem to be working. Thanks!
