### ISSUE TITLE
Sunlight Labs API Registration Link Down

### ISSUE THREAD

**Issue by AdminEACoalition** [propublica/congress#533]
The registration URL at [http://services.sunlightlabs.com/accounts/register/](http://services.sunlightlabs.com/accounts/register/) is returning with the following error:

## This site can’t be reached
**services.sunlightlabs.com**’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by TheTFo** [comment]
+1. I'd like to register

**Comment by kojoduncan** [comment]
+1 I'd like to register too

**Comment by dwillis** [comment]
Right now we are moving the API to ProPublica, and while some of the API is not back up yet, you should be able to make requests to it without needed an API key. We'll have some more details on next steps soon.

**Comment by fredbenenson** [comment]
Count me as interested in the API! Now is the time when we need this functionality the most, so your work is much appreciated!

**Comment by charman2** [comment]
Also the link at http://sunlightfoundation.com/api/accounts/register/ is redirecting to something irrelevant.

**Comment by mattnish** [comment]
Me too, would love an API key please!

**Comment by dwillis** [comment]
Thanks @fredbenenson & @charman2 - we don't control sunlightfoundation.com, so we can't fix that specific url, but we'll have something in place for API key signups soon. For now, @mattnish, you can make API calls without a key.

**Comment by kojoduncan** [comment]
Exactly which calls can be made without an API key? I tried https://propublica.github.io/congress-api-docs/#members and got nothing back.

**Comment by dwillis** [comment]
@kojoduncan The ProPublica Congress API still requires an API key, but the Sunlight Congress API does not for the time being.

**Comment by imcjeff** [comment]
@dwillis Will we be able to generate keys for the Open States API as well (http://sunlightlabs.github.io/openstates-api/)? I'm able to generate results from the Congress API without a key right now, but don't seem to be able to get results from Open States. Thanks for any info you can provide!

**Comment by dwillis** [comment]
@imcjeff Open States is an independent project now. You can find them at OpenStates.org.
