### ISSUE TITLE
Incorrect phone number for Congressman Deutch

### ISSUE THREAD

**Issue by cldwalker** [propublica/congress#541]
Hi. A bug was reported to me that the phone number for [Congressman Deutch](http://teddeutch.house.gov/) was incorrect. Sure enough the number, 202-225-9890, from [/legislators/locate](https://congress.api.sunlightfoundation.com/legislators/locate?longitude=-80.0896269&latitude=26.23075) and from /legislators doesn't match the number from his website 202-225-3001. I called and confirmed the incorrect number is for Congresswoman Frankel.

Thanks for this great resource!

**Comment by cldwalker** [comment]
@dwillis Is there a response here? Should data bug reports go somewhere else?

**Comment by dwillis** [comment]
@cldwalker Sorry - this was resolved.

**Comment by cldwalker** [comment]
Confirmed. Thanks for fixing!
