### ISSUE TITLE
115th congress status

### ISSUE THREAD

**Issue by cldwalker** [propublica/congress#542]
Hi. I noticed some data for the 115th congress is available e.g. Kamala Harris shows up but has no website. Is the new congress data incomplete until https://github.com/unitedstates/congress-legislators/issues/375 is done? If so, perhaps worth leaving this open or putting a mention in the readme. Thanks!

**Comment by cldwalker** [comment]
@dwillis Was this accidental? Could you provide a response here?

**Comment by dwillis** [comment]
@cldwalker Sorry! This is fixed now.

**Comment by cldwalker** [comment]
Thanks!
